# Generated by Django 2.0.2 on 2020-01-24 13:26

from django.conf import settings
import django.contrib.auth.password_validation
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import upload_validator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('blog_id', models.AutoField(primary_key=True, serialize=False)),
                ('blog_pic', models.ImageField(upload_to='images')),
                ('blog_description', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=2000)),
                ('date_commented', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Sayoneuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, validators=[django.core.validators.MinLengthValidator(5)])),
                ('mailid', models.EmailField(max_length=70)),
                ('username', models.CharField(max_length=70)),
                ('password', models.CharField(max_length=30, validators=[django.contrib.auth.password_validation.validate_password])),
                ('cnf_pass', models.CharField(max_length=30)),
                ('profile_pic', models.ImageField(blank=True, default='images/default_pic.jpg', null=True, upload_to='images', validators=[upload_validator.FileTypeValidator(allowed_types=['image/jpeg', 'image/png'])])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sayone_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('story_id', models.AutoField(primary_key=True, serialize=False)),
                ('story_author', models.CharField(max_length=50)),
                ('story_title', models.CharField(max_length=50)),
                ('story_likes', models.IntegerField(default=0)),
                ('story_type', models.IntegerField(choices=[(0, 'Event'), (1, 'Blog'), (2, 'Image Gallery')], default=0)),
                ('story_status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('story_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='like',
            name='story_liked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sayonestories.Story'),
        ),
        migrations.AddField(
            model_name='like',
            name='user_liked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='images',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_story', to='sayonestories.Story'),
        ),
        migrations.AddField(
            model_name='comments',
            name='story_commented',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_comment', to='sayonestories.Story'),
        ),
        migrations.AddField(
            model_name='comments',
            name='user_commented',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blog',
            name='story',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blog_story', to='sayonestories.Story'),
        ),
    ]
